cache:
  pipeline: [~/.npm]

shared:
  image: maven:3.6.3-jdk-8
  environment:
    NODE_VERSION: 14.16.1
    JOBS: 4

jobs:
  main:
    annotations:
      screwdriver.cd/ram: TURBO
      screwdriver.cd/cpu: TURBO
    steps:
      - install-chrome: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          apt-get update -qy
          apt-get install -qy google-chrome-stable
          ln -s /usr/bin/google-chrome /usr/bin/chrome
      - test: ./gradlew test
    requires:
      - ~commit
      - ~pr
